In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data_from_trip_practice_only.csv")
df.head()

,countrynameen,country_grouped,masterhotelid,masterhotelname,hotel_category,wkn_period,this_wk_in_cpn,this_wk_order,this_wk_uv,financial_revenue_past_4w,...,availability_tag,availability,bookable_ratio,lose_rate_final,lose_rate_tag,competitive_tag,hotelrating,htl_ct,htl_order_rank,top_pct_10
0,Malaysia,Malaysia,699489,"槟城火烈鸟海滩酒店(Flamingo Hotel by The Beach, Penang)",NaN,11/15/2021,0,188,2218,41296.01,...,A,0.9185,1.0,0.3165,B,B,4.2,2135,1,1
1,Malaysia,Malaysia,698563,吉隆坡棉兰东姑普雷斯科特酒店(Prescott Hotel Kuala Lumpur Med...,NaN,11/15/2021,0,147,707,16001.78,...,A,0.9162,1.0,0.2614,B,B,4.3,2135,2,1
2,Malaysia,Malaysia,698608,吉隆坡皇家朱兰酒店(Royale Chulan Kuala Lumpur),NaN,11/15/2021,0,141,1770,15879.86,...,A,0.9554,1.0,0.3057,B,B,4.4,2135,3,1
3,Malaysia,Malaysia,695037,KSL度假酒店(KSL Hotel & Resort),NaN,11/15/2021,0,128,1084,23672.91,...,A,0.9572,1.0,0.0635,A,A,4.4,2135,4,1
4,Malaysia,Malaysia,1465325,马六甲瑞园酒店(Swiss-Garden Hotel Melaka),NaN,11/15/2021,0,119,1773,28185.28,...,A,0.9094,1.0,0.1921,A,A,4.4,2135,5,1

## Normal use

In [3]:
df.query('this_wk_uv > 2000')  # same as df[ df["this_wk_uv"]>2000 ]

,countrynameen,country_grouped,masterhotelid,masterhotelname,hotel_category,wkn_period,this_wk_in_cpn,this_wk_order,this_wk_uv,financial_revenue_past_4w,...,availability_tag,availability,bookable_ratio,lose_rate_final,lose_rate_tag,competitive_tag,hotelrating,htl_ct,htl_order_rank,top_pct_10
0,Malaysia,Malaysia,699489,"槟城火烈鸟海滩酒店(Flamingo Hotel by The Beach, Penang)",NaN,11/15/2021,0,188,2218,41296.010,...,A,0.9185,1.0000,0.3165,B,B,4.2,2135,1,1
2135,Malaysia,Malaysia,699489,"槟城火烈鸟海滩酒店(Flamingo Hotel by The Beach, Penang)",NaN,10/25/2021,0,295,3287,19697.420,...,A,0.9790,0.9917,0.4533,B,B,4.1,1712,1,1
2136,Malaysia,Malaysia,1465325,马六甲瑞园酒店(Swiss-Garden Hotel Melaka),NaN,10/25/2021,0,195,2557,24621.040,...,B,0.8756,1.0000,0.2294,A,B,4.5,1712,2,1
2167,Malaysia,Malaysia,992455,迪克森海中天港口(Avillion Port Dickson),NaN,10/25/2021,0,52,2419,15692.890,...,B,0.7736,0.9750,0.3379,B,B,4.2,1712,33,1
3847,Malaysia,Malaysia,699489,"槟城火烈鸟海滩酒店(Flamingo Hotel by The Beach, Penang)",NaN,11/1/2021,0,188,2348,33430.750,...,B,0.8856,1.0000,0.4409,B,B,4.1,1872,1,1
3850,Malaysia,Malaysia,1465325,马六甲瑞园酒店(Swiss-Garden Hotel Melaka),NaN,11/1/2021,0,148,2431,32190.360,...,A,0.9282,1.0000,0.2802,B,B,4.5,1872,4,1
3855,Malaysia,Malaysia,992455,迪克森海中天港口(Avillion Port Dickson),NaN,11/1/2021,0,109,2490,16155.080,...,C,0.7013,1.0000,0.5145,C,C,4.2,1872,9,1
3857,Malaysia,Malaysia,993013,铂尔曼吉隆坡城市中心大酒店(Pullman Kuala Lumpur City Centre...,NaN,11/1/2021,0,102,2047,6347.266,...,A,0.9495,1.0000,0.6749,C,C,4.5,1872,11,1
3863,Malaysia,Malaysia,994074,"吉隆坡盛贸饭店(Traders Hotel, Kuala Lumpur)",NaN,11/1/2021,0,85,3778,4863.204,...,A,0.9655,1.0000,0.2568,B,B,4.7,1872,17,1
5719,Malaysia,Malaysia,699489,"槟城火烈鸟海滩酒店(Flamingo Hotel by The Beach, Penang)",NaN,11/8/2021,0,232,2626,39355.520,...,B,0.8585,1.0000,0.3926,B,B,4.2,2088,1,1
5722,Malaysia,Malaysia,1465325,马六甲瑞园酒店(Swiss-Garden Hotel Melaka),NaN,11/8/2021,0,142,2124,37503.760,...,B,0.8223,1.0000,0.1760,A,B,4.4,2088,4,1
7807,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,11/1/2021,0,753,6375,555083.800,...,A,0.9373,1.0000,0.0408,A,A,4.4,2821,1,1
7808,South Korea,South Korea,25673737,济州神话世界度假酒店-神话(Shinhwa Jeju Shinhwa World Hotel...,NaN,11/1/2021,0,243,2564,198502.900,...,A,0.9553,1.0000,0.0016,A,A,4.4,2821,2,1
7810,South Korea,South Korea,15677672,镜浦天空酒店(Skybay Hotel Gyeongpo),NaN,11/1/2021,0,209,2205,63769.010,...,A,0.9170,0.5333,0.6929,C,C,4.2,2821,4,1
10189,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,11/8/2021,0,653,4916,517816.200,...,A,0.9304,1.0000,0.0646,A,A,4.4,2671,1,1
11988,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,11/15/2021,0,625,4459,495468.100,...,A,0.9204,1.0000,0.0462,A,A,4.4,2757,1,1
14351,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,10/25/2021,0,1133,7762,593372.500,...,A,0.9253,1.0000,0.0513,A,A,4.5,2914,1,1
14352,South Korea,South Korea,25673737,济州神话世界度假酒店-神话(Shinhwa Jeju Shinhwa World Hotel...,NaN,10/25/2021,0,327,3083,173471.900,...,A,0.9598,1.0000,0.0038,A,A,4.4,2914,2,1
14353,South Korea,South Korea,7090954,济州君临海域酒店(Gloucester Hotel Jeju),NaN,10/25/2021,0,283,2044,43426.050,...,B,0.8499,0.9833,0.1362,A,B,4.4,2914,3,1
14354,South Korea,South Korea,15677672,镜浦天空酒店(Skybay Hotel Gyeongpo),NaN,10/25/2021,0,249,2727,57872.810,...,A,0.9031,0.5833,0.9405,C,C,4.1,2914,4,1

In [4]:
df.query('this_wk_uv > 2000 & this_wk_order > 200')

,countrynameen,country_grouped,masterhotelid,masterhotelname,hotel_category,wkn_period,this_wk_in_cpn,this_wk_order,this_wk_uv,financial_revenue_past_4w,...,availability_tag,availability,bookable_ratio,lose_rate_final,lose_rate_tag,competitive_tag,hotelrating,htl_ct,htl_order_rank,top_pct_10
2135,Malaysia,Malaysia,699489,"槟城火烈鸟海滩酒店(Flamingo Hotel by The Beach, Penang)",NaN,10/25/2021,0,295,3287,19697.42,...,A,0.9790,0.9917,0.4533,B,B,4.1,1712,1,1
5719,Malaysia,Malaysia,699489,"槟城火烈鸟海滩酒店(Flamingo Hotel by The Beach, Penang)",NaN,11/8/2021,0,232,2626,39355.52,...,B,0.8585,1.0000,0.3926,B,B,4.2,2088,1,1
7807,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,11/1/2021,0,753,6375,555083.80,...,A,0.9373,1.0000,0.0408,A,A,4.4,2821,1,1
7808,South Korea,South Korea,25673737,济州神话世界度假酒店-神话(Shinhwa Jeju Shinhwa World Hotel...,NaN,11/1/2021,0,243,2564,198502.90,...,A,0.9553,1.0000,0.0016,A,A,4.4,2821,2,1
7810,South Korea,South Korea,15677672,镜浦天空酒店(Skybay Hotel Gyeongpo),NaN,11/1/2021,0,209,2205,63769.01,...,A,0.9170,0.5333,0.6929,C,C,4.2,2821,4,1
10189,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,11/8/2021,0,653,4916,517816.20,...,A,0.9304,1.0000,0.0646,A,A,4.4,2671,1,1
11988,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,11/15/2021,0,625,4459,495468.10,...,A,0.9204,1.0000,0.0462,A,A,4.4,2757,1,1
14351,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,10/25/2021,0,1133,7762,593372.50,...,A,0.9253,1.0000,0.0513,A,A,4.5,2914,1,1
14352,South Korea,South Korea,25673737,济州神话世界度假酒店-神话(Shinhwa Jeju Shinhwa World Hotel...,NaN,10/25/2021,0,327,3083,173471.90,...,A,0.9598,1.0000,0.0038,A,A,4.4,2914,2,1
14353,South Korea,South Korea,7090954,济州君临海域酒店(Gloucester Hotel Jeju),NaN,10/25/2021,0,283,2044,43426.05,...,B,0.8499,0.9833,0.1362,A,B,4.4,2914,3,1
14354,South Korea,South Korea,15677672,镜浦天空酒店(Skybay Hotel Gyeongpo),NaN,10/25/2021,0,249,2727,57872.81,...,A,0.9031,0.5833,0.9405,C,C,4.1,2914,4,1

In [5]:
df.query('this_wk_uv > 2000 | this_wk_order > 200')

,countrynameen,country_grouped,masterhotelid,masterhotelname,hotel_category,wkn_period,this_wk_in_cpn,this_wk_order,this_wk_uv,financial_revenue_past_4w,...,availability_tag,availability,bookable_ratio,lose_rate_final,lose_rate_tag,competitive_tag,hotelrating,htl_ct,htl_order_rank,top_pct_10
0,Malaysia,Malaysia,699489,"槟城火烈鸟海滩酒店(Flamingo Hotel by The Beach, Penang)",NaN,11/15/2021,0,188,2218,41296.010,...,A,0.9185,1.0000,0.3165,B,B,4.2,2135,1,1
2135,Malaysia,Malaysia,699489,"槟城火烈鸟海滩酒店(Flamingo Hotel by The Beach, Penang)",NaN,10/25/2021,0,295,3287,19697.420,...,A,0.9790,0.9917,0.4533,B,B,4.1,1712,1,1
2136,Malaysia,Malaysia,1465325,马六甲瑞园酒店(Swiss-Garden Hotel Melaka),NaN,10/25/2021,0,195,2557,24621.040,...,B,0.8756,1.0000,0.2294,A,B,4.5,1712,2,1
2167,Malaysia,Malaysia,992455,迪克森海中天港口(Avillion Port Dickson),NaN,10/25/2021,0,52,2419,15692.890,...,B,0.7736,0.9750,0.3379,B,B,4.2,1712,33,1
3847,Malaysia,Malaysia,699489,"槟城火烈鸟海滩酒店(Flamingo Hotel by The Beach, Penang)",NaN,11/1/2021,0,188,2348,33430.750,...,B,0.8856,1.0000,0.4409,B,B,4.1,1872,1,1
3850,Malaysia,Malaysia,1465325,马六甲瑞园酒店(Swiss-Garden Hotel Melaka),NaN,11/1/2021,0,148,2431,32190.360,...,A,0.9282,1.0000,0.2802,B,B,4.5,1872,4,1
3855,Malaysia,Malaysia,992455,迪克森海中天港口(Avillion Port Dickson),NaN,11/1/2021,0,109,2490,16155.080,...,C,0.7013,1.0000,0.5145,C,C,4.2,1872,9,1
3857,Malaysia,Malaysia,993013,铂尔曼吉隆坡城市中心大酒店(Pullman Kuala Lumpur City Centre...,NaN,11/1/2021,0,102,2047,6347.266,...,A,0.9495,1.0000,0.6749,C,C,4.5,1872,11,1
3863,Malaysia,Malaysia,994074,"吉隆坡盛贸饭店(Traders Hotel, Kuala Lumpur)",NaN,11/1/2021,0,85,3778,4863.204,...,A,0.9655,1.0000,0.2568,B,B,4.7,1872,17,1
5719,Malaysia,Malaysia,699489,"槟城火烈鸟海滩酒店(Flamingo Hotel by The Beach, Penang)",NaN,11/8/2021,0,232,2626,39355.520,...,B,0.8585,1.0000,0.3926,B,B,4.2,2088,1,1
5722,Malaysia,Malaysia,1465325,马六甲瑞园酒店(Swiss-Garden Hotel Melaka),NaN,11/8/2021,0,142,2124,37503.760,...,B,0.8223,1.0000,0.1760,A,B,4.4,2088,4,1
7807,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,11/1/2021,0,753,6375,555083.800,...,A,0.9373,1.0000,0.0408,A,A,4.4,2821,1,1
7808,South Korea,South Korea,25673737,济州神话世界度假酒店-神话(Shinhwa Jeju Shinhwa World Hotel...,NaN,11/1/2021,0,243,2564,198502.900,...,A,0.9553,1.0000,0.0016,A,A,4.4,2821,2,1
7809,South Korea,South Korea,4548893,海蓝丽景酒店(Hotel Regent Marine the Blue),NaN,11/1/2021,0,228,1941,60563.290,...,B,0.8610,1.0000,0.3614,B,B,4.4,2821,3,1
7810,South Korea,South Korea,15677672,镜浦天空酒店(Skybay Hotel Gyeongpo),NaN,11/1/2021,0,209,2205,63769.010,...,A,0.9170,0.5333,0.6929,C,C,4.2,2821,4,1
10189,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,11/8/2021,0,653,4916,517816.200,...,A,0.9304,1.0000,0.0646,A,A,4.4,2671,1,1
11988,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,11/15/2021,0,625,4459,495468.100,...,A,0.9204,1.0000,0.0462,A,A,4.4,2757,1,1
11989,South Korea,South Korea,25673737,济州神话世界度假酒店-神话(Shinhwa Jeju Shinhwa World Hotel...,NaN,11/15/2021,0,234,1793,181326.500,...,A,0.9931,1.0000,0.0063,A,A,4.4,2757,2,1
14351,South Korea,South Korea,12093236,济州神话世界度假酒店 – 蓝鼎(Landing Jeju Shinhwa World Hot...,NaN,10/25/2021,0,1133,7762,593372.500,...,A,0.9253,1.0000,0.0513,A,A,4.5,2914,1,1
14352,South Korea,South Korea,25673737,济州神话世界度假酒店-神话(Shinhwa Jeju Shinhwa World Hotel...,NaN,10/25/2021,0,327,3083,173471.900,...,A,0.9598,1.0000,0.0038,A,A,4.4,2914,2,1
14353,South Korea,South Korea,7090954,济州君临海域酒店(Gloucester Hotel Jeju),NaN,10/25/2021,0,283,2044,43426.050,...,B,0.8499,0.9833,0.1362,A,B,4.4,2914,3,1
14354,South Korea,South Korea,15677672,镜浦天空酒店(Skybay Hotel Gyeongpo),NaN,10/25/2021,0,249,2727,57872.810,...,A,0.9031,0.5833,0.9405,C,C,4.1,2914,4,1